export default {
  SELECT_CHANNEL: 'SELECT_CHANNEL',
  INVALID_CHANNEL: 'INVALID_CHANNEL',
  REQUEST_CHANNEL: 'REQUEST_CHANNEL',
  RECEIVE_CHANNEL: 'RECEIVE_CHANNEL',
  EXPIRED_CHANNEL: 'EXPIRED_CHANNEL'
};
